version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./:/server
    ports:
      - "4000:4000"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=discussionforum"
  database:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
volumes:
  db: